version: '3'

services:
  worker:
    build: .
      # build: .
      # dockerfile: Dockerfile
    container_name: "worker_service"
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
